services:
  ipfsjs-gcs:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
      - "4002:4002"
      - "4003:4003"
      - "5002:5002"
      - "9090:9090"
    volumes:
      - ./src:/usr/app/src
      - ./package.json:/usr/app/package.json
    command: npm run dev