apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs-gcs
  labels:
    app: ipfs-gcs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ipfs-gcs
  template:
    metadata:
      labels:
        app: ipfs-gcs
    spec:
      containers:
      - name: ipfs-gcs
        image: your-registry/ipfs-gcs-example:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: ipfs-gcs-config
              key: bucket-name
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gcs-key