apiVersion: v1
kind: Service
metadata:
  name: ipfs-gcs
  labels:
    app: ipfs-gcs
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: ipfs-gcs
---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-gcs-internal
  labels:
    app: ipfs-gcs
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: ipfs-gcs